server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zhang-yichen2001/config.git
#          search-paths: config-repo # 配置文件在GitHub仓库中的路径
          clone-on-start: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
